[package]
name = "chapter_01"
version = "0.1.0"
authors = ["bartholomews <github@bartholomews.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.2.0"
num = "0.4.0"